# Hugo Configuration file
# baseURL: 'https://sirajudheen.netlify.app/'
baseURL: /
languageCode: en-us
title: Blog

# https://github.com/sirajudheenam/hugoPaper.git
theme: hugoPaper
sectionPagesMenu: 'main'
markup.highlight.noClasses: false

# Paper Theme related
disqusShortname: 'sirajudheen-blog-netlify-app' # add disqus comments
# color style
color: 'gray' # linen, wheat, gray, light
# header social icons
twitter: 'ali_sirajudheen' # twitter.com/YOUR_TWITTER_ID
github: 'sirajudheenam' # github.com/YOUR_GITHUB_ID
instagram: 'buzzmesam' # instagram.com/YOUR_INSTAGRAM_ID
rss: true # show rss icon with link

# home page profile
avatar: 'sirajudheenam@gmail.com' # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
name: 'Sirajudheen Mohamed Ali'
bio: 'Simple guy with simple life'

# misc
disableHLJS: true # disable requesting highlight.js
monoDarkIcon: true # show monochrome dark mode icon

# debug
debug: true
